### ISSUE TITLE
OpenToonz module

### ISSUE THREAD

**Issue by morevnaproject** [morevnaproject/RenderChan#27]
I wonder, can we have OpenToonz module? ^__^

**Comment by scribblemaniac** [comment]
I would say no for the time being. It doesn't look like they have a command line interface, so that would have to be patched first. The file format looks like xml, but I'm a little weary since they don't include the standard `<?xml version="1.0" ?>` tag, and their way of storing sets of data (bounding boxes, points, ranges, anything you'd represent multiple variables) is questionable. For example `<stereoscopic>0 0.05</stereoscopic>`, what are these values? Why couldn't they do something logical and easier to read and parse like `<stereoscopic x-offset="0.05" y-offset="0" />` or whatever the proper labels for those values are. Now they probably aren't going to change the format any time soon since they started off with a 1.0 release it's a lot more work to migrate from existing formats.

As for the patch, I don't really want to go anywhere near that project at the moment. Between the people making tons of changes to get it to compile on linux, to those coming up with issue after issue about how seemingly nothing works on the currently supported operating systems, to ui that is missing major components and looks like it's running on System 7, to the pull requests that are sitting around collecting dust, it's an absolute mess right now in my opinion and I want nothing to do with it until they get their stuff together.

\</rant>

**Comment by morevnaproject** [comment]
This is exactly my position. ^__^ For this moment I prefer to stay away and watch for the general dynamic of development. I think it's good thing that OpenToonz got much attention from developers. But I would like to watch who will do what and remaining gaps uncovered. And that I will be able to determine the best place to put my contributions. Right now I have enough work with Morevna's episode. ^__^

**Comment by scribblemaniac** [comment]
> Right now I have enough work with Morevna's episode. ^___^

:heart: I'm so excited for this! ^_^ Keep up the good work!

**Comment by morevnaproject** [comment]
The work on OpenToonz side is done - https://github.com/blackwarthog/opentoonz/commit/e015a5aadeb47906306f93f040d218dec3fd32c9

Now OpenToonz can be instructed to execute a script from a commandline.

The feature will be shipped in OpenToonz Morevna Edition 1.2.1.1.

**Comment by ave4** [comment]
I think I've found an easy way to render toonz scenes from the command line:

`tcomposer "/home/km2/Документы/OpenToonz/linux-microsoft-s/linux-und-microsoft/scenes/005.tnz" -o "/home/km2/Документы/OpenToonz/linux-microsoft-s/linux-und-microsoft/outputs/005.mp4" -range 1 87 -step 1 -shrink 1 -multimedia 0 -nthreads single -maxtilesize none`

Or
`tcomposer "/home/km2/.config/OpenToonz/stuff/sandbox/scenes/testrender.tnz" -o "/home/km2/.config/OpenToonz/stuff/sandbox/outputs/testrender.tif" -range 1 13 -step 1 -shrink 1 -multimedia 0 -nthreads all -maxtilesize none`

**Comment by morevnaproject** [comment]
Oh! Thank you so much!  I wasn't aware about that. I was thinking about generating a script and calling it through CLI, but this approach is much simpler! Thanks a lot!

**Comment by ave4** [comment]
Да ладно, а это что? https://morevnaproject.org/2016/11/27/use-opentoonz-cli/

**Comment by ave4** [comment]
Я это случайно увидел: 
![Снимок экрана от 2020-08-04 23-17-22](https://user-images.githubusercontent.com/35303790/89329895-e8fd8500-d6a8-11ea-81b5-5c534c05833d.png)

**Comment by morevnaproject** [comment]
> Да ладно, а это что? https://morevnaproject.org/2016/11/27/use-opentoonz-cli/

Я работал только с `tconverter `, а про `tcomposer` не знал. Точнее знал, но думал что он для другого.

Не хочешь попробовать написать модуль для RenderChan? Там в принципе всё просто, если что я подскажу. А иначе у меня так руи и не дойдут. ^__^

**Comment by ave4** [comment]
> Не хочешь попробовать написать модуль для RenderChan? Там в принципе всё просто, если что я подскажу. А иначе у меня так руи и не дойдут. ^__^

На питоне я ничего сложнее hello world не писал, но если всё просто то почему бы нет.

**Comment by morevnaproject** [comment]
Главное, это знать про отситупы ^___^

Все модули находятся вот здесь - https://github.com/morevnaproject-org/RenderChan/tree/master/renderchan/contrib

Проще всего будет скопировать модуль `synfig.py` и написать на его основе.
https://github.com/morevnaproject-org/RenderChan/blob/master/renderchan/contrib/synfig.py

Ключевая функция, которая отвечает за рендеринаг называется `render()`.

Вторая важная функция - `analyze()` - отвечает за сбор зависимостей для файла который рендерится. Нужно собирать только прямые зависимости - то есть, те файлы, на которые непосредственно ссылается файл TNZ.

**Comment by morevnaproject** [comment]
@ave4 Как там дела? Получается что-нибудь?
Я предлагаю сделать черновой Pull-Request (недоделанный) и можно по ходу обсуждать что и как сделать. ^__^

**Comment by ave4** [comment]
Это оказалось сложнее чем я думал. В частности на функции analyze() не могу распарсить tnz-файл. Вот что выходит:

```
[bin]$ ./renderchan /home/123/Документы/OpenToonz/renderchan_otz/scenes/001.tnz
RenderChan initialized.
Loading module: blender...
Loading module: zip...
Loading module: flac...
Loading module: opentoonz...
Loading module: synfig...
Module warning (synfig): Cannot find 'synfig' executable.
    Please install synfig package.
Warning: Unable load module - synfig.
Loading module: list...
Loading module: vorbis...
Loading module: inkscape...
Loading module: gimp...
Loading module: mp3...
Loading module: pencil2d...
Module warning (pencil2d): Cannot find 'pencil2d' executable.
    Please install pencil2d package.
Warning: Unable load module - pencil2d.
Loading module: ffmpeg...
Loading module: krita...
. Analyzing file: ../../../Документы/OpenToonz/renderchan_otz/scenes/001.tnz
Traceback (most recent call last):
  File "./renderchan", line 63, in <module>
    _start_renderchan()
  File "./renderchan", line 56, in _start_renderchan
    sys.exit(cli.main(datadir, sys.argv))
  File "/home/km2/make/RenderChan/renderchan/cli.py", line 215, in main
    return renderchan.submit(filename, args.dependenciesOnly, args.allocateOnly, args.stereo)
  File "/home/km2/make/RenderChan/renderchan/core.py", line 150, in submit
    taskfile = RenderChanFile(filename, self.modules, self.projects)
  File "/home/km2/make/RenderChan/renderchan/file.py", line 79, in __init__
    info=self.module.analyze(self.getPath())
  File "/home/km2/make/RenderChan/renderchan/contrib/opentoonz.py", line 31, in analyze
    tree = ElementTree.parse(f)
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 1202, in parse
    tree.parse(source, parser)
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 595, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 82, column 77


Execution time: 00:00:00 

Cache closed.
```
Как я понял у меня кривой xml

**Comment by morevnaproject** [comment]
Ооооо, где-то я уже слышал что в OpenToonz некорректный XML - https://github.com/synfig/synfig/issues/1449#issuecomment-643582792

**Comment by morevnaproject** [comment]
Можно попробовать прочитать файл и сделать в нём замены (исправить ошибки XML) и только после этого отдать парсеру xml.etree.

**Comment by ave4** [comment]
Ну что ж, с горем пополам завёл модуль тунза для renderchan. Но есть один ньюанс, в tcomposer нет опции для задания другого разрешения сцен, поэтому оно всегда рендерит в дефолтном разрешение.

**Comment by morevnaproject** [comment]
Привет! Возникла такая идея: а что если RenderChan будет считывать tnz-файл (построчно) и записывать его в другой временный tnz-файл, при этом исправляя ошибки XML - там нужно просто заменить "& " на "&amp; " (имено с пробелом в конце строки!). Тогда мы получим корректный XML, который можно распарсить.

Про ширину-высоту - можно решить так же. Просто создать временный файл, в котором переписаны значения ширины-высоты и рендерить его. Это, конечно, костыль, но как временное решение вполне подойдёт.

**Comment by ave4** [comment]
Ну я подумаю, но странно если там баг в одном пробеле то почему его не могут исправить?

**Comment by morevnaproject** [comment]
Ну, не совсем "в одном пробеле". ^__^ Там бага в том, что по стандарту XML символ "&" должен кодироваться как "&amp;". Но этого не происходит. А использование символа "&" просто так - запрещено.

Но да, исправить это было бы неплохо. Но как быть со старыми файлами?

**Comment by ave4** [comment]
Мой патч влили https://github.com/opentoonz/opentoonz/pull/3599

**Comment by morevnaproject** [comment]
Ваааау! Надо добавить в Morevna Edition и сделать сборку ^__^
