### ISSUE TITLE
Renderchan не видит Pencil2D

### ISSUE THREAD

**Issue by ave4** [morevnaproject/RenderChan#55]
При попытке отрендерить проект, где используется pencil2d происходит ошибка:

```
[km2@loffice bin]$ ./renderchan /run/media/km2/f2160ded-0321-4e51-ac50-37bb6717fefb/video/renderchan/project-sentence.blend
RenderChan initialized.
Loading module: vorbis...
Loading module: inkscape...
Loading module: flac...
Loading module: synfig...
Loading module: ffmpeg...
Loading module: krita...
Loading module: blender...
Loading module: list...
Loading module: pencil2d...
qt5ct: using qt5ct plugin
Detect locale =  "ru"
Load translation =  true
Install translation =  true
WARNING: Failed to initialize Pencil2D module. The possible reasons for that could be: missing X connection, or the version of Pencil2D on your system is unsupported (too old?). In latter case please consider to get latest version at https://www.pencil2d.org/.
Warning: Unable load module - pencil2d.
Loading module: zip...
Loading module: gimp...
Loading module: mp3...
. Analyzing file: ...51-ac50-37bb6717fefb/video/renderchan/project-sentence.blend
. . Cache found
. Analyzing file: ...7bb6717fefb/video/renderchan/render/940-soldiers/boy.sif.png
. . Cache found
Traceback (most recent call last):
  File "./renderchan", line 63, in <module>
    _start_renderchan()
  File "./renderchan", line 56, in _start_renderchan
    sys.exit(cli.main(datadir, sys.argv))
  File "/home/km2/make/RenderChan/renderchan/cli.py", line 215, in main
    return renderchan.submit(filename, args.dependenciesOnly, args.allocateOnly, args.stereo)
  File "/home/km2/make/RenderChan/renderchan/core.py", line 300, in submit
    self.addToGraph(taskfile, dependenciesOnly, allocateOnly)
  File "/home/km2/make/RenderChan/renderchan/core.py", line 430, in addToGraph
    self.parseRenderDependency(taskfile, allocateOnly, self.dry_run, self.force)
  File "/home/km2/make/RenderChan/renderchan/core.py", line 527, in parseRenderDependency
    (isDirtyValue, tasklist, maxTime)=self.parseDirectDependency(taskfile, compareTime, dryRun, force)
  File "/home/km2/make/RenderChan/renderchan/core.py", line 777, in parseDirectDependency
    dep_isDirty = self.parseRenderDependency(dependency, False, dryRun, force)
  File "/home/km2/make/RenderChan/renderchan/core.py", line 527, in parseRenderDependency
    (isDirtyValue, tasklist, maxTime)=self.parseDirectDependency(taskfile, compareTime, dryRun, force)
  File "/home/km2/make/RenderChan/renderchan/core.py", line 779, in parseDirectDependency
    raise Exception("No module to render file" + dependency.getPath())
Exception: No module to render file/run/media/km2/f2160ded-0321-4e51-ac50-37bb6717fefb/video/renderchan/940-soldiers/boy.pcl


Execution time: 00:00:00 

Cache closed.
```

При этом у меня установлена самая последняя версия Pencil2D. Которая прекрасно открывает pcl сцены вручную.

**Comment by ave4** [comment]
Pencil2D версии 0.6.4. Пересобрал с git'а, не помогло.

**Comment by morevnaproject** [comment]
Доброго времени суток! А что выдаёт команда ```which pencil2d```?

**Comment by ave4** [comment]
```
[km2@loffice bin]$ which pencil2d
/usr/bin/pencil2d
```
За это время я наткнулся на это:
```
[km2@loffice bin]$ pencil2d -v
qt5ct: using qt5ct plugin
Detect locale =  "ru"
Load translation =  true
Install translation =  true
Pencil2D 0.6.4
Ошибка сегментирования (стек памяти сброшен на диск)
```


```
[km2@loffice bin]$ pencil2d -h
qt5ct: using qt5ct plugin
Detect locale =  "ru"
Load translation =  true
Install translation =  true
Использование: pencil2d [параметры] input
Pencil2D - это программа для рисования и анимации для Mac OS X, Windows и Linux. Она позволяет создавать традиционную рисованную анимацию (мультфильм) с использованием как растровой, так и векторной графики.

Параметры:
  -h, --help                    Показать эту справку.
  -v, --version                 Показать сведения о версии.
  -o, --export <выходной_путь>  Визуализировать файл в <output_path>
  --camera <имя_слоя>           Название используемого слоя камеры
  --width <целое>               Ширина выходных кадров
  --height <целое>              Высота выходных кадров
  --start <кадр>                Первый кадр, который вы хотите включить в
                                экспортированный фильм
  --end <кадр>                  Последний кадр, который вы хотите включить в
                                экспортированный фильм. Также может быть
                                последним или последний звук, чтобы
                                автоматически использовать последний кадр,
                                содержащий анимацию или звук, соответственно
  --transparency                Визуализировать прозрачность когда это возможно

Аргументы:
  input                         Путь к входному файлу карандаша.
malloc_consolidate(): invalid chunk size
Аварийный останов (стек памяти сброшен на диск)
```

**Comment by ave4** [comment]
Похоже это баг pencil2d

**Comment by ave4** [comment]
Кажется я понял в чём дело! qt5ct мешал. Я его отключил картина изменилась.

```
RenderChan initialized.
Loading module: vorbis...
Loading module: inkscape...
Loading module: flac...
Loading module: synfig...
Loading module: ffmpeg...
Loading module: krita...
Loading module: blender...
Loading module: list...
Loading module: pencil2d...
Detect locale =  "ru"
Load translation =  true
Install translation =  true
Loading module: zip...
Loading module: gimp...
Loading module: mp3...
. Analyzing file: ...1-ac50-37bb6717fefb/renderchan/nastya-in-heart/project.blend
. . Cache found
. Analyzing file: ...enderchan/nastya-in-heart/render/06/6.sifz.png/file.0020.png
. . Cache found
. Analyzing file: ...enderchan/nastya-in-heart/render/06/6.sifz.png/file.0177.png
. . Cache found
. Analyzing file: ...tya-in-heart/render/04-road-letter/04.sifz.png/file.0029.png
. . Cache found
. Analyzing file: .../renderchan/nastya-in-heart/render/04-road-letter/01.pcl.lst
. . Cache found
   Skipping file /run/media/km2/f2160ded-0321-4e51-ac50-37bb6717fefb/renderchan/nastya-in-heart/04-road-letter/01.pcl.data/004.014.png...
Rendering: 0.0
Unexpected error: <class 'KeyError'>
Traceback (most recent call last):
  File "./renderchan", line 63, in <module>
    _start_renderchan()
  File "./renderchan", line 56, in _start_renderchan
    sys.exit(cli.main(datadir, sys.argv))
  File "/home/km2/make/RenderChan/renderchan/cli.py", line 215, in main
    return renderchan.submit(filename, args.dependenciesOnly, args.allocateOnly, args.stereo)
  File "/home/km2/make/RenderChan/renderchan/core.py", line 300, in submit
    self.addToGraph(taskfile, dependenciesOnly, allocateOnly)
  File "/home/km2/make/RenderChan/renderchan/core.py", line 417, in addToGraph
    self.parseDirectDependency(taskfile, None, self.dry_run, self.force)
  File "/home/km2/make/RenderChan/renderchan/core.py", line 777, in parseDirectDependency
    dep_isDirty = self.parseRenderDependency(dependency, False, dryRun, force)
  File "/home/km2/make/RenderChan/renderchan/core.py", line 527, in parseRenderDependency
    (isDirtyValue, tasklist, maxTime)=self.parseDirectDependency(taskfile, compareTime, dryRun, force)
  File "/home/km2/make/RenderChan/renderchan/core.py", line 777, in parseDirectDependency
    dep_isDirty = self.parseRenderDependency(dependency, False, dryRun, force)
  File "/home/km2/make/RenderChan/renderchan/core.py", line 580, in parseRenderDependency
    self.job_render(taskfile, taskfile.getFormat(), self.updateCompletion, start, end, compare_time)
  File "/home/km2/make/RenderChan/renderchan/core.py", line 971, in job_render
    params)
  File "/home/km2/make/RenderChan/renderchan/contrib/pencil2d.py", line 105, in render
    if extraParams['camera']:
KeyError: 'camera'


Execution time: 00:00:01 

Cache closed.
```

**Comment by scribblemaniac** [comment]
Renderchan might not work properly with a version of Pencil2D built from source unless you pass the following flags to qmake: `CONFIG+=release DEFINES+=QT_NO_DEBUG_OUTPUT`. Otherwise it will try and read the debug messages.

I have not seen those memory errors before. What are your system specifications (OS/distro, architecture, etc.)?

**Comment by ave4** [comment]
Arch Linux, x86-64
AUR pencil2d-git and pencil2d

**Comment by scribblemaniac** [comment]
You may have more luck trying to the use the AppImage version: https://github.com/pencil2d/pencil/releases/download/v0.6.4/pencil2d-linux-amd64-0.6.4.AppImage. Just run `chmod +x` on that and then put it somewhere in your path and uninstall the other versions.

The [flatpak](https://flathub.org/apps/details/org.pencil2d.Pencil2D) is another option for Linux users which is better if you are planning on making animations with sound in the GUI.

**Comment by morevnaproject** [comment]
> qt5ct мешал

Got that. I believe I will be able to fix that in RenderChan's module.

> KeyError: 'camera'

I can confirm the same error here. Needs fixing. I will look at it...

**Comment by ave4** [comment]
@scribblemaniac I tried the same thing

**Comment by morevnaproject** [comment]
@ave4 Apologies for delay. `KeyError: 'camera'` issue is fixed now. Should render fine.

Working on qt5ct issue. ^__^

**Comment by morevnaproject** [comment]
@ave4  `qt5ct` also fixed now. ^__^

**Comment by ave4** [comment]
Прекрасно теперь *.pcl рендерятся, но при попытки отрендерить *.pclx файл вылетает ошибка:

`ERROR: The '.pclx' file type was not recoginized.`

**Comment by ave4** [comment]
Я в pencil2d.py на 82 строке выпилил проверку, вроде заработало.

**Comment by morevnaproject** [comment]
Сделайте, пожалуйста, новый issue для проблемы с pclx ^__^
