### ISSUE TITLE
RenderChan necessarily requires Krita

### ISSUE THREAD

**Issue by ave4** [morevnaproject/RenderChan#56]
Здравствуйте!
Запустил renderchan на другом компьютере (на котором не установлена Krita). Чтобы я не запускал везде Renderchan ругается на отсутствие бинарника `krita`, даже если он вообще не нужен.

**Comment by ave4** [comment]
```
[km2@loffice RenderChan]$ bin/renderchan "/home/km2/Видео/blender video/video.blend" 
RenderChan initialized.
Loading module: blender...
Loading module: zip...
Loading module: flac...
Loading module: synfig...
Module warning (synfig): Cannot find 'synfig' executable.
    Please install synfig package.
Warning: Unable load module - synfig.
Loading module: list...
Loading module: vorbis...
Module warning (vorbis): Cannot find 'oggdec' executable!
    Please install vorbis-tools package.
Warning: Unable load module - vorbis.
Loading module: inkscape...
Loading module: gimp...
Loading module: mp3...
Loading module: pencil2d...
Module warning (pencil2d): Cannot find 'pencil2d' executable.
    Please install pencil2d package.
Warning: Unable load module - pencil2d.
Loading module: ffmpeg...
Traceback (most recent call last):
  File "bin/renderchan", line 63, in <module>
    _start_renderchan()
  File "bin/renderchan", line 56, in _start_renderchan
    sys.exit(cli.main(datadir, sys.argv))
  File "/home/km2/make/RenderChan/renderchan/cli.py", line 133, in main
    renderchan = RenderChan()
  File "/home/km2/make/RenderChan/renderchan/core.py", line 35, in __init__
    self.modules = RenderChanModuleManager()
  File "/home/km2/make/RenderChan/renderchan/module.py", line 12, in __init__
    self.loadAll()
  File "/home/km2/make/RenderChan/renderchan/module.py", line 46, in loadAll
    self.load(filename)
  File "/home/km2/make/RenderChan/renderchan/module.py", line 32, in load
    module = moduleClass()
  File "/home/km2/make/RenderChan/renderchan/contrib/krita.py", line 32, in __init__
    out = subprocess.Popen(commandline, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] Нет такого файла или каталога: 'krita': 'krita'


Execution time: 00:00:00 
```

**Comment by ave4** [comment]
Затычка из `sudo ln -s /bin/true /bin/krita` решила проблему.

**Comment by ave4** [comment]
```
[km2@loffice RenderChan]$ bin/renderchan "/home/km2/Видео/blender video/video.blend" 
RenderChan initialized.
Loading module: blender...
Loading module: zip...
Loading module: flac...
Loading module: synfig...
Module warning (synfig): Cannot find 'synfig' executable.
    Please install synfig package.
Warning: Unable load module - synfig.
Loading module: list...
Loading module: vorbis...
Loading module: inkscape...
Loading module: gimp...
Loading module: mp3...
Loading module: pencil2d...
Module warning (pencil2d): Cannot find 'pencil2d' executable.
    Please install pencil2d package.
Warning: Unable load module - pencil2d.
Loading module: ffmpeg...
Loading module: krita...
Warning: File /home/km2/Видео/blender video/video.blend doesn't belong to any project.
. Analyzing file: ../../Видео/blender video/video.blend
  Blender command failed...

ERROR: Can't render a file which is not a part of renderchan project.



Execution time: 00:00:01 

```
Наверное это из-за нового Blender 2.80?

**Comment by morevnaproject** [comment]
Спасибо, я посмотрю в чём там дело! ^__^

**Comment by morevnaproject** [comment]
Fixed now. Thanks for reporting! ^__^
